import { createSlice } from '@reduxjs/toolkit'

const initialState = {
    user: {
        id: null,
        username: null,
        isAuthenticated: false
    },
}
  
// Create Redux state slice
const userSlice = createSlice({
  name: 'user',
  initialState, // Define initial state
  reducers: {
    // Define reducers
    ADD_USER: (state, action) => {
        state.user = action.payload
    },
    RESET_USER: (state, action) => {
      state.user = {}
    }
  },
})

// Export actions generated by "createSlice()":
export const { ADD_USER,RESET_USER } = userSlice.actions
  
// Export reducer generated by "createSlice()":
export default userSlice.reducer